project:
  type: website
  output-dir: docs

website:
  title: "Macbeth Ahortor"

  page-footer:
    left: "&copy; Macbeth Ahortor, 2024"
    right: |
      <a href="mailto:macbethahortor@gmail.com" class="footer-button">
        <i class="bi bi-envelope-fill"></i> Gmail
      </a>
      <a href="https://www.linkedin.com/in/mcbethahortor/" target="_blank" class="footer-button">
        <i class="bi bi-linkedin"></i> LinkedIn
      </a>
      <a href="https://github.com/mahortor" target="_blank" class="footer-button">
        <i class="bi bi-github"></i> GitHub
      </a>
    

  navbar:
    pinned: false
    logo: Ahortor_Mcbeth_profile.jpg
    right:
      - href: index.qmd
        text: Home

      - href: background.qmd
        text: Background
        
      - href: teaching.qmd
        text: Teaching
        
      - href: resume.qmd
        text: Resume

format:
  html: 
    fontsize: 1.0em
    mainfont: century gothic
    fontcolor: "#000000" 
    theme: 
      - lux
      - theme.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true

