project:
  type: website
  output-dir: docs

website:
  title: "Macbeth Ahortor"

  page-footer:
    left: "&copy; Copyright 2024, Macbeth Ahortor"
    right: ""

  navbar:
    pinned: true
    logo: Ahortor_Mcbeth_profile.jpg
    right:
      - href: index.qmd
        text: Home

      - href: background.qmd
        text: Background
        
      - href: teaching.qmd
        text: Teaching
        
      - href: resume.qmd
        text: Resume

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true



