project:
  type: website
  output-dir: docs

website:
  title: "Macbeth Ahortor"

  page-footer:
    left: "&copy; Copyright 2024, Macbeth Ahortor"
    right: ""

  navbar:
    right:
      - href: index.qmd
        text: Home

      - href: background.qmd
        text: Background
        
      - href: teaching.qmd
        text: Teaching
        
      - href: resume.qmd
        text: resume

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



